config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :presentations

  mount Ckeditor::Engine => '/ckeditor'

  resources :checks

  resources :activities

  resources :chapters

  resources :courses

  resources :catalogs

  get '/:id/checked_in' , to: 'activities#list' , as: 'show_checked_in'

  # You can have the root of your site routed with "root"
  root 'activities#index'

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base

  has_attached_file :photo, :styles => { :medium => "600x300>" , :small => "100x50>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  belongs_to :activity
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:show, :edit, :update, :destroy]

  layout "activity"

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: 'Presentation was successfully created.' }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: 'Presentation was successfully updated.' }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: 'Presentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:photo, :description, :activity_id)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= simple_form_for(@presentation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :photo %>
    <%= f.input :description %>
    <%= f.association :activity %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing presentation</h1>

<%= render 'form' %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<h1>Listing presentations</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Photo</th>
      <th>Description</th>
      <th>Belongs to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= image_tag presentation.photo.url(:small) %></td>
        <td><%= presentation.description %></td>
        <th><%= presentation.activity %></th>
        <td><%= link_to 'Show', presentation %></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New presentation</h1>

<%= render 'form' %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%= @presentation.photo %>
</p>

<p>
  <strong>Description:</strong>
  <%= @presentation.description %>
</p>

<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>