config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :presentations

  mount Ckeditor::Engine => '/ckeditor'

  resources :checks

  resources :activities

  resources :chapters

  resources :courses

  resources :catalogs

  get '/:id/checked_in' , to: 'activities#list' , as: 'show_checked_in'

  # You can have the root of your site routed with "root"
  root 'activities#index'

end

app/models/check.rb
class Check < ActiveRecord::Base
  belongs_to :activity

  validates :name , :presence => true
  validates :phone , :presence => true
  validates :email , :presence => true
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :set_check, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:show, :edit, :update, :destroy]
  layout "activity"
  # GET /checks
  # GET /checks.json
  def index
    @checks = Check.all
  end

  # GET /checks/1
  # GET /checks/1.json
  def show
  end

  # GET /checks/new
  def new
    @check = Check.new
  end

  # GET /checks/1/edit
  def edit
  end

  # POST /checks
  # POST /checks.json
  def create
    @check = Check.new(check_params)

    @activity = Activity.find(@check.activity_id)

    respond_to do |format|
      if @check.save
        format.html { redirect_to @activity, notice: "Ok." }
        format.json { render :show, status: :created, location: @check }
      else
        format.html { render :new }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checks/1
  # PATCH/PUT /checks/1.json
  def update
    respond_to do |format|
      if @check.update(check_params)
        format.html { redirect_to @check, notice: 'Check was successfully updated.' }
        format.json { render :show, status: :ok, location: @check }
      else
        format.html { render :edit }
        format.json { render json: @check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checks/1
  # DELETE /checks/1.json
  def destroy
    @check.destroy
    respond_to do |format|
      format.html { redirect_to checks_url, notice: 'Check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check
      @check = Check.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_params
      params.require(:check).permit(:activity_id, :name, :phone, :email, :job, :company, :description)
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/checks/_form.html.erb
<%= simple_form_for(@check) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :activity %>
    <%= f.input :name %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :job %>
    <%= f.input :company %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/checks/edit.html.erb
<h1>Editing check</h1>

<%= render 'form' %>

<%= link_to 'Show', @check %> |
<%= link_to 'Back', checks_path %>

app/views/checks/index.html.erb
<h1>Listing checks</h1>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Job</th>
      <th>Company</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checks.each do |check| %>
      <tr>
        <td><%= check.activity %></td>
        <td><%= check.name %></td>
        <td><%= check.phone %></td>
        <td><%= check.email %></td>
        <td><%= check.job %></td>
        <td><%= check.company %></td>
        <td><%= check.description %></td>
        <td><%= link_to 'Show', check %></td>
        <td><%= link_to 'Edit', edit_check_path(check) %></td>
        <td><%= link_to 'Destroy', check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check', new_check_path %>

app/views/checks/new.html.erb
<h1>New check</h1>

<%= render 'form' %>

<%= link_to 'Back', checks_path %>

app/views/checks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @check.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @check.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @check.email %>
</p>

<p>
  <strong>Job:</strong>
  <%= @check.job %>
</p>

<p>
  <strong>Company:</strong>
  <%= @check.company %>
</p>

<p>
  <strong>Description:</strong>
  <%= @check.description %>
</p>

<%= link_to 'Edit', edit_check_path(@check) %> |
<%= link_to 'Back', checks_path %>