config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :presentations

  mount Ckeditor::Engine => '/ckeditor'

  resources :checks

  resources :activities

  resources :chapters

  resources :courses

  resources :catalogs

  get '/:id/checked_in' , to: 'activities#list' , as: 'show_checked_in'

  # You can have the root of your site routed with "root"
  root 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :checks
  has_many :presentations

  def to_s
    self.subject
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :list, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:index, :update, :destroy]

  layout "activity"
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show

    @check = Check.new
    @qr = RQRCode::QRCode.new( request.original_url , :size => 4, :level => :l )
  end

  def list
    @checks = Check.where(:activity_id => @activity.id).all
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:subject, :content, :expired_at)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for(@activity) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.cktext_area :content %>
    <%= f.input :expired_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table class="table table-bordered table-condensed">
  <thead>
    <tr>
      <th>Subject</th>
      <th>Expired at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.subject %></td>
        <td><%= activity.expired_at %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/list.html.erb
<div class="col-md-36">
  <div class="panel"><div class="panel-body">
<table class="table">
    <tr>
      <td>名字/昵称</td>
      <td>工作</td>
      <td>备注信息</td>
    </tr>
    <% @checks.each do |f| %>

        <% if f.name != '' %>
          <tr>
          <td><%= f.name %></td>
          <td><%= f.job %></td>
          <td><%= f.description %></td>
          </tr>
        <% end %>

    <% end %>
</table>
      </div></div>
</div>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<% content_for :title do %><%= @activity.subject %><% end %>

<div class="col-md-36 hidden-sm hidden-xs" align="center">
<ul id="featured">
    <% @activity.presentations.each do |p| %>
    <li>
        <%= image_tag p.photo.url%>
    </li>
  <% end %>
</ul>
</div>
<style type="text/css">
    table {
        border-width: 0;
        border-style: none;
        border-color: #0000ff;
        border-collapse: collapse;
    }
    td {
        border-width: 0;
        border-style: none;
        border-color: #0000ff;
        border-collapse: collapse;
        padding: 0;
        margin: 0;
        width: 5px;
        height: 5px;
    }
    td.black { background-color: #000; }
    td.white { background-color: #fff; }
</style>
<div class="col-md-18">
    <div class="panel"><div class="panel-body">

      <a class="hidden-md hidden-lg btn btn-lg btn-block btn-primary" href="#form">立即报名</a>

    <p>
      <h3><%= @activity.subject %></h3>
    </p>

    <p>
      <%= @activity.content.html_safe %>
    </p>

    <p>
      <strong>活动截止日期:</strong>
      <%= @activity.expired_at.to_formatted_s(:db) %>
    </p>

      <% if current_admin %>
        <%= link_to 'Edit', edit_activity_path(@activity) %> |
        <%= link_to 'Back', activities_path %>
      <% end %>

    </div></div>
</div>

<div class="col-md-18">
  <div id="form" class="panel"><div class="panel-body">

    <div class="shadow hidden-sm hidden-xs" align="center">
    <table>
      <% @qr.modules.each_index do |x| %>
          <tr>
            <% @qr.modules.each_index do |y| %>
                <% if @qr.dark?(x,y) %>
                    <td class="black"/>
                <% else %>
                    <td class="white"/>
                <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
    扫一扫微信分享
    </div>

    <h4>报名表</h4>

    <%= simple_form_for(@check) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :activity_id , :label => '姓名', :as => :hidden , :input_html => { :value => @activity.id } %>
          <%= f.input :name , :label => '姓名' %>
          <%= f.input :phone , :label => '手机号' %>
          <%= f.input :email , :label => '邮箱' %>
          <%= f.input :job , :label => '工作' %>
          <%= f.input :company , :label => '公司名' %>
          <%= f.input :description , :label => '自我介绍' %>
        </div>

        <div class="form-actions">
          <%= f.button :submit , '报名' , :class => 'btn btn-primary btn-lg btn-block' %>
        </div>
    <% end %>


  </div></div>
</div>


<script>
    $(document).ready(function() {
        $("#featured").zAccordion({
            easing: 'easeOutBounce',
            timeout: 2500,
            slideWidth: 600,
            width: 900,
            height: 310
        });
    });

    $('.shadow')
            .shadow('perspective');
    $('img').shadow('lifted');
</script>